#############################################################################
# Config for SkyGrid ${version}
##############################################################################

general:   
   # Grid height - max is 256
   gridheight: 128
   
   # Spawn height - height where players will spawn. Can be less than the grid height
   spawnheight: 128

   # Name of the world - if it does not exist then it will be generated.
   worldName: ASkyGrid
   # Create a Grid Nether - if this is true, the nether grid world will be made.
   createnether: true
   # Create a Grid End - if this is true, the end grid world will be made.
   # If true, end portal frames will be generated at the bottom of the overworld grid.
   createend: true
   # The probability of a frame being created in a chunk. Frames are always at y=0.
   endframeprobability: 0.05

   # Overworld has biomes - this will affect some block types and tree types.
   biomes: true
   # Allow saplings to grow into trees sometimes.
   growtrees: true

   # The center point around which players will randomly spawn. Format: x,z
   spawncenter: 10000,10000
   # Distance around spawn center point where players will randomly spawn
   # Example, 1000 will randomly spawn players between -1000,-1000 to 1000, 1000
   # around the spawncenter point.
   # If you are using world guard claims, make sure this is a large figure to minimize
   # the chances of a player landing in a claimed spot. The plugin will try to avoid that
   # but it may be impossible.
   distance: 10000

   # Respawn at home after death.
   # If false, players will respawn at the server default location or world.
   # This may get overriden by other plugins.
   respawnathome: true

   # Protection radius given when planting a Welcome Sign - requires WorldGuard.
   # This is optional. You can use other plugins to provide protection areas, like
   # stones, or grief prevention plugins.
   # If a player removes their sign, the WG region protection is removed.
   # Set the entry and exit text in locale.yml or set to "" to have no text.
   #
   # Setting to 0 will disable protection and remove any protection regions.
   # Setting this to a larger number will not change any current warp signs and protection
   # will only start when a new warp sign is made.
   #
   # Players can be given larger spaces with the askygrid.protectionradius.# permission
   # where # is a number greater than the default. It will only be used with the next
   # warp sign (it does not increase current protection ranges).
   protectionRange: 0
    
   # Warp sound - for 1.8 servers, use BAT_TAKEOFF. 
   # Latest sound options can be found at:
   # https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
   warpsound: ENTITY_BAT_TAKEOFF
      
   # Banned commands - these commands cannot be run by players in the world
   # Bypass by Op or with the askygrid.mod.bannedcommands permission
   # The spawner command should be banned otherwise chaos will ensue!
   bannedcommands:
   - spawner
   
   # Remove mobs - this kills all monsters in the vicinity when the player logs in. 
   loginremovemobs: false

   # Remove mobs when /asg.
   gridremovemobs: false
   
   # Mob white list - these mobs will NOT be removed when logging in or doing /asg
   # Options are: Blaze, Cave_Spider, Creeper, Enderman, Endermite, Giant, Guardian,
   # Pig_Zombie, Silverfish, Skeleton, Spider, Witch, Wither, Zombie
   mobwhitelist:
   - Wither
   - Enderman
   - Pig_Zombie

   # Sets the limit for number of monsters that can spawn in a chunk in this world. 
   # Note: this does not limit the number of monsters, just how many spawn naturally.
   # Note: If set to a negative number the world will use the server-wide spawn limit instead.
   # Max is 100
   monsterspawnlimit: 70
   
   # Sets the limit for number of animals that can spawn in a chunk in this world. 
   # Note: If set to a negative number the world will use the server-wide spawn limit instead.
   # Max is 100
   animalspawnlimit: 15
   
   # Sets the limit for number of water animals [squid] that can spawn in a chunk in this world. 
   # Note: If set to a negative number the world will use the server-wide spawn limit instead.
   # Max is 100
   wateranimalspawnlimit: 15

   ##### Economy ######
   # Use economy or not. If true, an economy plugin is required. If false,
   # no money is used or given by challenges.
   # If there is no economy plugin present anyway, money will be automatically
   # disabled.
   useeconomy: true

   # Reset Money - if this is true, will reset the player's money to
   # the starting money (see below) when they start.
   # Recommendation is that this is set to true, but if you run multi-worlds
   # make sure your economy handles multi-worlds too.
   resetmoney: false

   # Starting money - this is how much money new players will have as their
   # balance at the start. 
   startingmoney: 0

   # Reset Ender Chest - if true, the player's Ender Chest will be cleared when they
   # start ASkyGrid. Default is false.
   # NOTE: Ender Chests span worlds, so it will clear ALL chests. In general,
   # Enderchests should not be allowed in ASkyGrid unless you only run the ASkyGrid
   # world.
   resetenderchest: false

   # Broadcast 1st time challenge completion messages to all players.
   # Change to false if the spam becomes too much.
   broadcastmessages: true

   # Allow /island teleport when falling. If set to false, all teleporting is
   # disabled until death from the void or until you hit something.
   # See commands that this will block too.
   allowfallingteleport: true
   blockingcommands:
   - home
   #- anotherCommand
   #- andAnotherOne

   # Remove non-repeatable challenges from the challenge GUI when complete
   removecompleteonetimechallenges: false

   # Add enchanted glow to completed challenges (does not work with all clients)
   # Also currently adds an "enchanted" line of text...
   addcompletedglow: true

   # Default maximum number of homes a player can have. Min = 1
   # Accessed via sethome <number> or go <number>
   # Use this permission to set for specific user groups: askyblock.island.maxhomes.<number>  
   maxhomes: 1

   # Warp panel - GUI for welcome warp signs. If set to false, old-style
   # text will be used
   usewarppanel: true
   
   # Mute death messages
   mutedeathmessages: false
   
   # Config.yml version. DO NOT EDIT. This number only changes if the latest
   # plugin config has been updated. If a new config is detected, it will be
   # auto-saved to config.new.yml.
   version: ${version}

# World block types. If the material cannot be placed, bedrock will be used.
# Format: Material : Probability
# Block types must be Bukkit Material types.
# Chests have different items in them in different world types.
world:
   # Over world blocks. Beware of making too many chests, they can lag a lot.
   blocks:
     BOOKSHELF: 3
     BROWN_MUSHROOM: 2
     CACTUS: 10
     CHEST: 1
     CLAY: 2
     COAL_ORE: 20
     DEAD_BUSH: 3
     DIAMOND_ORE: 1
     DIRT: 10
     DOUBLE_PLANT: 10
     GLASS: 1
     GOLD_ORE: 10
     GRASS: 60
     GRAVEL: 10
     IRON_ORE: 20
     LAPIS_ORE: 5
     LEAVES: 30
     LOG: 40
     LONG_GRASS: 10
     MELON: 5
     MOB_SPAWNER: 2
     MOSSY_COBBLESTONE: 5
     MYCEL: 15
     OBSIDIAN: 5
     PISTON_BASE: 1
     PISTON_STICKY_BASE: 1
     PUMPKIN: 5
     PRISMARINE: 1
     RED_ROSE: 10
     RED_MUSHROOM: 2
     REDSTONE_ORE: 8
     SAND: 20
     SANDSTONE: 10
     SAPLING: 10
     SEA_LANTERN: 1
     SNOW_BLOCK: 8
     STATIONARY_LAVA: 1
     STATIONARY_WATER: 10
     STONE: 120
     SUGAR_CANE_BLOCK: 2
     TNT: 2
     WEB: 10
     WOOL: 25
     YELLOW_FLOWER: 2
   # Nether block types
   netherblocks:
   # Beware with glowstone and lava - the lighting calcs will lag the
   # server badly if there are too many blocks.
     STATIONARY_LAVA: 5
     GRAVEL: 30
     MOB_SPAWNER: 2
     CHEST: 2
     NETHERRACK: 300
     SOUL_SAND: 100
     GLOWSTONE: 2
     NETHER_BRICK: 30
     NETHER_FENCE: 10
     NETHER_BRICK_STAIRS: 15
     NETHER_WARTS: 30
     QUARTZ_ORE: 10
   # The End blocks. END_CRYSTAL is blocked because it causes serious performance issues.
   endblocks:
     OBSIDIAN: 10
     ENDER_STONE: 500
     MOB_SPAWNER: 1
     CHEST: 1
     END_BRICKS: 100
     CHORUS_PLANT: 3
     STAINED_GLASS: 1
     END_ROD: 5
     PURPUR_BLOCK: 10
     PURPUR_PILLAR: 10
     PURPUR_STAIRS: 8
     PURPUR_SLAB: 10
