# SkyGrid Configuration ${version}
#
skygrid:
  command:
    # Island Command. What command users will run to access their island.
    # To define alias, just separate commands with white space.
    island: skygrid sg
    # The island admin command.
    # To define alias, just separate commands with white space.
    admin: sgadmin sga
world:
  chest-fill:
    # Chest fill setting. 1 = normal, 0 = nothing, 1+ for more items
    overworld: 1
    # Nether chest fill setting
    nether: 1
    # The End chest fill setting
    end: 1
  # World block types. If the material cannot be placed, bedrock will be used.
  # Format: Material : Probability
  # Block types must be Bukkit Material types.
  # Chests have different items in them in different world types.
  # Over world blocks. Beware of making too many chests, they can lag a lot.
  blocks:
    BROWN_MUSHROOM: 8
    STRIPPED_SPRUCE_LOG: 8
    SANDSTONE: 120
    RED_SAND: 20
    ACACIA_LOG: 20
    TNT: 1
    FERN: 4
    BOOKSHELF: 10
    PINK_TULIP: 8
    STRIPPED_ACACIA_LOG: 1
    OAK_WOOD: 19
    JUNGLE_SAPLING: 19
    WHITE_TULIP: 2
    CACTUS: 6
    SPRUCE_WOOD: 9
    BLUE_ORCHID: 1
    PUMPKIN: 9
    STRIPPED_ACACIA_WOOD: 1
    STRIPPED_BIRCH_LOG: 1
    WHEAT: 4
    STRIPPED_OAK_LOG: 1
    CHEST: 5
    GRASS_PATH: 7
    STRIPPED_BIRCH_WOOD: 1
    SPRUCE_LOG: 3
    STRIPPED_DARK_OAK_WOOD: 1
    RED_MUSHROOM: 8
    SPRUCE_SAPLING: 2
    REDSTONE_ORE: 2
    TALL_GRASS: 13
    DEAD_BUSH: 1
    DARK_OAK_SAPLING: 3
    GRASS_BLOCK: 200
    EMERALD_ORE: 5
    COAL_ORE: 70
    PETRIFIED_OAK_SLAB: 1
    SUNFLOWER: 3
    INFESTED_COBBLESTONE: 1
    DIORITE: 2
    STRIPPED_OAK_WOOD: 1
    FARMLAND: 7
    POPPY: 5
    DARK_OAK_WOOD: 18
    GOLD_ORE: 3
    DARK_OAK_LOG: 10
    CLAY: 5
    LILAC: 7
    DARK_PRISMARINE: 3
    STRIPPED_JUNGLE_LOG: 1
    PODZOL: 4
    ACACIA_LEAVES: 8
    GRASS: 100
    STRIPPED_SPRUCE_WOOD: 1
    LARGE_FERN: 8
    FIRE_CORAL_BLOCK: 1
    GRANITE: 50
    SAND: 50
    SUGAR_CANE: 4
    JUNGLE_LEAVES: 10
    JUNGLE_WOOD: 20
    BONE_BLOCK: 1
    RED_TULIP: 3
    SPAWNER: 5
    JUNGLE_LOG: 17
    MOSSY_COBBLESTONE: 1
    PRISMARINE: 3
    DANDELION: 16
    ALLIUM: 12
    ACACIA_WOOD: 16
    OAK_SAPLING: 11
    PEONY: 7
    LAVA: 5
    STRIPPED_DARK_OAK_LOG: 1
    OBSIDIAN: 1
    AZURE_BLUET: 1
    OXEYE_DAISY: 6
    DARK_OAK_LEAVES: 9
    GRAVEL: 20
    SEA_LANTERN: 1
    MELON: 15
    COBWEB: 7
    COARSE_DIRT: 17
    LAPIS_ORE: 6
    ACACIA_SAPLING: 17
    OAK_LOG: 10
    BIRCH_SAPLING: 8
    BEETROOTS: 9
    STRIPPED_JUNGLE_WOOD: 1
    BIRCH_LOG: 2
    BIRCH_WOOD: 16
    MYCELIUM: 2
    DIAMOND_ORE: 1
    RED_SANDSTONE: 19
    OAK_LEAVES: 4
    IRON_ORE: 10
    SPRUCE_LEAVES: 9
    SPONGE: 1
    SNOW_BLOCK: 1
    ORANGE_TULIP: 10
    BIRCH_LEAVES: 9
    ANDESITE: 90
    STONE: 180
    ROSE_BUSH: 8
  nether:
    # Generate SkyGrid Nether - if this is false, the nether world will not be made
    generate: true
    # Nether trees are made if a player grows a tree in the nether (gravel and glowstone)
    trees: true
    # Nether block types
    # Beware with glowstone and lava - the lighting calcs will lag the
    # server badly if there are too many blocks.
    blocks:
      SOUL_SAND: 90
      LAVA: 1
      NETHER_QUARTZ_ORE: 15
      MAGMA_BLOCK: 1
      NETHER_WART_BLOCK: 12
      GRAVEL: 10
      SPAWNER: 2
      CHEST: 15
      NETHER_WART: 19
      NETHERRACK: 200
      COBWEB: 7
      GLOWSTONE: 1
      RED_NETHER_BRICKS: 12
  end:
    # Generate SkyGrid End - if this is false, the end world will not be made
    generate: true
    # The End blocks. END_CRYSTAL is blocked because it causes serious performance issues.
    blocks:
      CHEST: 5
      END_ROD: 1
      CHORUS_PLANT: 2
      OBSIDIAN: 1
      END_STONE: 200
      GRAVEL: 10
      SPAWNER: 5
      PURPUR_BLOCK: 10
  # Overworld has biomes - this will affect some block types and tree types.
  create-biomes: true
  # The probability of a frame being created in a chunk. Frames are always at y=0.
  end-frame-probability: 0.1
  # Allow saplings to grow into trees sometimes.
  grow-trees: true
  # Friendly name for this world. Used in admin commands. Must be a single word
  friendly-name: SkyGrid
  # Name of the world - if it does not exist then it will be generated.
  # It acts like a prefix for nether and end
  world-name: skygrid-world
  # World difficulty setting - PEACEFUL, EASY, NORMAL, HARD
  # Other plugins may override this setting
  difficulty: NORMAL
  # Start at these coordinates.
  start-x: 0
  start-z: 0
  # SkyGrid height
  # This is the height of the top sky grid layer
  skygrid-height: 128
  # Spawn height
  # Height where players will spawn. Can be less than the grid height
  spawn-height: 128
  # Space around new players in blocks (will be rounded up to nearest 16 blocks)
  space-around-players: 1000
  # Default protection radius around player's home (so total size is 2x this)
  protection-range: 50
  # The default game mode for this world. Players will be set to this mode when they create
  # a new island for example. Options are SURVIVAL, CREATIVE, ADVENTURE, SPECTATOR
  default-game-mode: SURVIVAL
  # The maximum number of players a player can ban at any one time in this game mode.
  # The permission acidarea.ban.maxlimit.X where X is a number can also be used per player
  # -1 = unlimited
  ban-limit: -1
  # Mob white list - these mobs will NOT be removed when logging in or doing /island
  remove-mobs-whitelist:
  - GUARDIAN
  - ZOMBIE_VILLAGER
  - WITHER
  - PIG_ZOMBIE
  # World flags. These are boolean settings for various flags for this world
  flags:
    OBSIDIAN_SCOOPING: true
    ENTER_EXIT_MESSAGES: true
    ISLAND_RESPAWN: true
    LIQUIDS_FLOWING_OUT: false
    REMOVE_END_EXIT_ISLAND: true
    REMOVE_MOBS: true
    TREES_GROWING_OUTSIDE_RANGE: false
    PREVENT_TELEPORT_WHEN_FALLING: false
    NATURAL_SPAWNING_OUTSIDE_RANGE: true
  # These are the default protection settings protected areas.
  # The value is the minimum island rank required to do the action
  # Ranks are: Visitor = 0, Member = 900, Owner = 1000
  default-protection-flags:
    HURT_ANIMALS: 500
    REDSTONE: 500
    BUCKET: 500
    LOCK: 0
    ENDER_PEARL: 500
    DOOR: 500
    FURNACE: 500
    ANVIL: 500
    MINECART: 500
    FISH_SCOOPING: 500
    FIRE: 500
    END_PORTAL: 500
    BREEDING: 500
    HURT_VILLAGERS: 500
    TNT: 500
    TURTLE_EGGS: 500
    FROST_WALKER: 500
    COLLECT_LAVA: 500
    LEVER: 500
    RIDING: 500
    HURT_MONSTERS: 500
    ARMOR_STAND: 500
    NAME_TAG: 500
    TRADING: 500
    EGGS: 500
    ITEM_DROP: 500
    NOTE_BLOCK: 500
    NETHER_PORTAL: 500
    CROP_TRAMPLE: 500
    ITEM_PICKUP: 500
    BREWING: 500
    DROPPER: 500
    COLLECT_WATER: 500
    BUTTON: 500
    FIRE_EXTINGUISH: 500
    BEACON: 500
    TRAPDOOR: 500
    PRESSURE_PLATE: 500
    PLACE_BLOCKS: 500
    ITEM_FRAME: 500
    CRAFTING: 500
    ENCHANTING: 500
    SHEARING: 500
    BOAT: 500
    BED: 500
    SPAWN_EGGS: 500
    MILKING: 500
    DISPENSER: 500
    GATE: 500
    EXPERIENCE_PICKUP: 500
    HOPPER: 500
    LEASH: 500
    MOUNT_INVENTORY: 500
    BREAK_BLOCKS: 500
    CHORUS_FRUIT: 500
    CONTAINER: 500
    JUKEBOX: 500
    POTION_THROWING: 500
  # These are the default settings for new protected areas
  default-settings:
    PVP_END: false
    PVP_NETHER: false
    ANIMAL_SPAWN: true
    MONSTER_SPAWN: true
    FIRE_SPREAD: true
    PVP_OVERWORLD: false
  # These settings/flags are hidden from users
  # Ops can toggle hiding in-game using SHIFT-LEFT-CLICK on flags in settings
  hidden-flags: []
  # Visitor banned commands - Visitors to islands cannot use these commands in this world
  visitor-banned-commands: []
area:
  # Default max team size
  # Permission size cannot be less than the default below. 
  max-team-size: 4
  reset:
    # How many resets a player is allowed (override with /sgadmin clearresets <player>)
    # Value of -1 means unlimited, 0 means hardcore - no resets.
    # Example, 2 resets means they get 2 resets or 3 islands lifetime
    reset-limit: -1
    # Kicked or leaving players lose resets
    # Players who leave a team will lose a reset chance
    # If a player has zero resets left and leaves a team, they cannot make a new
    # island by themselves and can only join a team.
    # Leave this true to avoid players exploiting free islands
    leavers-lose-reset: false
    # Allow kicked players to keep their inventory.
    # If false, kicked player's inventory will be thrown at the leader if the
    # kicked player is online and in the world.
    kicked-keep-inventory: false
    on-join:
      # What should reset when the player joins or starts new
      # Reset Money - if this is true, will reset the player's money to the starting money
      # Recommendation is that this is set to true, but if you run multi-worlds
      # make sure your economy handles multi-worlds too.
      money: false
      # Reset inventory - if true, the player's inventory will be cleared.
      # Note: if you have MultiInv running or a similar inventory control plugin, that
      # plugin may still reset the inventory when the world changes.
      inventory: false
      # Reset Ender Chest - if true, the player's Ender Chest will be cleared.
      ender-chest: false
    on-leave:
      # What should reset when the player leaves or is kicked
      # Reset Money - if this is true, will reset the player's money to the starting money
      # Recommendation is that this is set to true, but if you run multi-worlds
      # make sure your economy handles multi-worlds too.
      money: false
      # Reset inventory - if true, the player's inventory will be cleared.
      # Note: if you have MultiInv running or a similar inventory control plugin, that
      # plugin may still reset the inventory when the world changes.
      inventory: false
      # Reset Ender Chest - if true, the player's Ender Chest will be cleared.
      ender-chest: false
  sethome:
    nether:
      allow: true
      require-confirmation: true
    the-end:
      allow: true
      require-confirmation: true
  deaths:
    # Whether deaths are counted or not.
    counted: true
    # Maximum number of deaths to count. The death count can be used by add-ons.
    max: 10
    sum-team: false
    # When a player joins a team, reset their death count
    team-join-reset: true
protection:
  # Geo restrict mobs.
  # Mobs that exit the protected space where they were spawned will be removed.
  geo-limit-settings: []
  # Invincible visitors. List of damages that will not affect visitors.
  # Make list blank if visitors should receive all damages
  invincible-visitors: []
do-not-edit-these-settings:
  # These settings should not be edited
  reset-epoch: 0
uniqueId: config
