# SkyGrid Configuration 0.0.1-SNAPSHOT
# This config file is dynamic and saved when the server is shutdown.
# You cannot edit it while the server is running because changes will
# be lost! Use in-game settings GUI or edit when server is offline.
# 
world:
  # World block types. If the material cannot be placed, bedrock will be used.
  # Format: Material : Probability
  # Block types must be Bukkit Material types.
  # Chests have different items in them in different world types.
  # Over world blocks. Beware of making too many chests, they can lag a lot.
  blocks:
    BROWN_MUSHROOM: 8
    STRIPPED_SPRUCE_LOG: 8
    SANDSTONE: 120
    RED_SAND: 20
    ACACIA_LOG: 20
    FERN: 4
    TNT: 1
    BOOKSHELF: 10
    PINK_TULIP: 8
    STRIPPED_ACACIA_LOG: 1
    JUNGLE_SAPLING: 19
    OAK_WOOD: 19
    WHITE_TULIP: 2
    CACTUS: 6
    SPRUCE_WOOD: 9
    BLUE_ORCHID: 1
    STRIPPED_ACACIA_WOOD: 1
    PUMPKIN: 9
    STRIPPED_BIRCH_LOG: 1
    WHEAT: 4
    STRIPPED_OAK_LOG: 1
    CHEST: 5
    GRASS_PATH: 7
    STRIPPED_BIRCH_WOOD: 1
    SPRUCE_LOG: 3
    RED_MUSHROOM: 8
    STRIPPED_DARK_OAK_WOOD: 1
    SPRUCE_SAPLING: 2
    REDSTONE_ORE: 2
    TALL_GRASS: 13
    DEAD_BUSH: 1
    DARK_OAK_SAPLING: 3
    GRASS_BLOCK: 200
    EMERALD_ORE: 5
    COAL_ORE: 70
    PETRIFIED_OAK_SLAB: 1
    SUNFLOWER: 3
    INFESTED_COBBLESTONE: 1
    DIORITE: 2
    STRIPPED_OAK_WOOD: 1
    FARMLAND: 7
    POPPY: 5
    DARK_OAK_WOOD: 18
    GOLD_ORE: 3
    DARK_OAK_LOG: 10
    CLAY: 5
    LILAC: 7
    DARK_PRISMARINE: 3
    STRIPPED_JUNGLE_LOG: 1
    PODZOL: 4
    ACACIA_LEAVES: 8
    GRASS: 100
    LARGE_FERN: 8
    STRIPPED_SPRUCE_WOOD: 1
    GRANITE: 50
    FIRE_CORAL_BLOCK: 1
    SAND: 50
    SUGAR_CANE: 4
    JUNGLE_LEAVES: 10
    JUNGLE_WOOD: 20
    BONE_BLOCK: 1
    RED_TULIP: 3
    SPAWNER: 5
    JUNGLE_LOG: 17
    MOSSY_COBBLESTONE: 1
    PRISMARINE: 3
    DANDELION: 16
    ALLIUM: 12
    ACACIA_WOOD: 16
    PEONY: 7
    OAK_SAPLING: 11
    STRIPPED_DARK_OAK_LOG: 1
    LAVA: 5
    OBSIDIAN: 1
    AZURE_BLUET: 1
    OXEYE_DAISY: 6
    DARK_OAK_LEAVES: 9
    GRAVEL: 20
    SEA_LANTERN: 1
    MELON: 15
    COBWEB: 7
    COARSE_DIRT: 17
    LAPIS_ORE: 6
    ACACIA_SAPLING: 17
    BIRCH_SAPLING: 8
    OAK_LOG: 10
    BEETROOTS: 9
    STRIPPED_JUNGLE_WOOD: 1
    BIRCH_LOG: 2
    BIRCH_WOOD: 16
    MYCELIUM: 2
    DIAMOND_ORE: 1
    RED_SANDSTONE: 19
    OAK_LEAVES: 4
    IRON_ORE: 10
    SPRUCE_LEAVES: 9
    SPONGE: 1
    SNOW_BLOCK: 1
    BIRCH_LEAVES: 9
    ORANGE_TULIP: 10
    ANDESITE: 90
    STONE: 180
    ROSE_BUSH: 8
  # Nether block types
  # Beware with glowstone and lava - the lighting calcs will lag the
  # server badly if there are too many blocks.
  netherblocks:
    SOUL_SAND: 90
    LAVA: 1
    NETHER_QUARTZ_ORE: 15
    MAGMA_BLOCK: 1
    NETHER_WART_BLOCK: 12
    GRAVEL: 10
    SPAWNER: 2
    CHEST: 15
    NETHERRACK: 200
    NETHER_WART: 19
    COBWEB: 7
    GLOWSTONE: 1
    RED_NETHER_BRICKS: 12
  # The End blocks. END_CRYSTAL is blocked because it causes serious performance issues.
  endblocks:
    CHEST: 5
    END_ROD: 1
    OBSIDIAN: 1
    CHORUS_PLANT: 2
    END_STONE: 200
    GRAVEL: 10
    SPAWNER: 5
    PURPUR_BLOCK: 10
  # Overworld has biomes - this will affect some block types and tree types.
  create-biomes: true
  # The probability of a frame being created in a chunk. Frames are always at y=0.
  end-frame-probability: 0.05
  # Allow saplings to grow into trees sometimes.
  grow-trees: true
  # Friendly name for this world. Used in admin commands. Must be a single word
  friendly-name: SkyGrid
  # Name of the world - if it does not exist then it will be generated.
  # It acts like a prefix for nether and end
  world-name: SkyGrid-world
  # World difficulty setting - PEACEFUL, EASY, NORMAL, HARD
  # Other plugins may override this setting
  difficulty: NORMAL
  # Start at these coordinates.
  start-x: 0
  start-z: 0
  # SkyGrid height
  # This is the height of the top sky grid layer
  skygrid-height: 128
  # Spawn height
  # Height where players will spawn. Can be less than the grid height
  spawn-height: 128
  # The default game mode for this world. Players will be set to this mode when they create
  # a new island for example. Options are SURVIVAL, CREATIVE, ADVENTURE, SPECTATOR
  default-game-mode: SURVIVAL
  nether:
    # Generate Nether - if this is false, the nether world will not be made and access to
    # the nether will not occur. Other plugins may still enable portal usage.
    generate: true
    # Nether trees are made if a player grows a tree in the nether (gravel and glowstone)
    # Applies to both vanilla and islands Nether
    trees: true
  end:
    generate: true
    # /!\ This feature is experimental and might not work as expected or might not work at all.
    dragon-spawn: false
  # World flags. These are boolean settings for various flags for this world
  flags:
    OBSIDIAN_SCOOPING: true
    ENTER_EXIT_MESSAGES: true
    REMOVE_MOBS: true
  # These are the default protection settings for new islands.
  # The value is the minimum island rank required allowed to do the action
  # Ranks are: Visitor = 0, Member = 900, Owner = 1000
  default-island-flags:
    HURT_ANIMALS: 500
    REDSTONE: 500
    BUCKET: 500
    LOCK: 0
    ENDER_PEARL: 500
    DOOR: 500
    FURNACE: 500
    ANVIL: 500
    FIRE: 500
    FISH_SCOOPING: 500
    END_PORTAL: 500
    BREEDING: 500
    TNT: 500
    HURT_VILLAGERS: 500
    TURTLE_EGGS: 500
    FROST_WALKER: 500
    COLLECT_LAVA: 500
    LEVER: 500
    HURT_MONSTERS: 500
    RIDING: 500
    NAME_TAG: 500
    ARMOR_STAND: 500
    TRADING: 500
    EGGS: 500
    ITEM_DROP: 500
    NOTE_BLOCK: 500
    NETHER_PORTAL: 500
    CROP_TRAMPLE: 500
    ITEM_PICKUP: 500
    BREWING: 500
    DROPPER: 500
    COLLECT_WATER: 500
    BUTTON: 500
    FIRE_EXTINGUISH: 500
    BEACON: 500
    TRAPDOOR: 500
    PRESSURE_PLATE: 500
    ITEM_FRAME: 500
    PLACE_BLOCKS: 500
    CRAFTING: 500
    ENCHANTING: 500
    SHEARING: 500
    BED: 500
    SPAWN_EGGS: 500
    MILKING: 500
    DISPENSER: 500
    GATE: 500
    EXPERIENCE_PICKUP: 500
    HOPPER: 500
    LEASH: 500
    BREAK_BLOCKS: 500
    MOUNT_INVENTORY: 500
    CHORUS_FRUIT: 500
    CONTAINER: 500
    JUKEBOX: 500
  # These are the default settings for new islands
  default-island-settings:
    PVP_END: false
    PVP_NETHER: false
    ANIMAL_SPAWN: true
    MONSTER_SPAWN: true
    FIRE_SPREAD: true
    PVP_OVERWORLD: false
  # These are the settings visible to users. (Not implemented yet)
  # /!\ This feature is experimental and might not work as expected or might not work at all.
  visible-settings: []
useOwnGenerator: false
seaHeight: 0
maxIslands: -1
banLimit: -1
netherIslands: true
netherSpawnRadius: 32
endIslands: true
removeMobsWhitelist: []
visitorBannedCommands: []
do-not-edit-these-settings:
  # These settings should not be edited
  reset-epoch: 0
uniqueId: config
